### ISSUE TITLE
杂合基因型

### ISSUE THREAD

**Issue by Wangchangsh** [venyao/binQTL#2]
姚师兄，我的群体为自交5代的RIL，其中仍有较多的杂合bin，这些杂合区段如何处理？population指定为RIL和F2是否只考虑基因型种类，不考虑显性效应？我还使用了icim模型，检测功效明显高于binQTL的模型，这个模型有后续改进方案吗？

**Comment by venyao** [comment]
你的数据如果使用binQTL的话，我建议群体设置为F2。模型不涉及显性效应。binQTL的检出率并不是最好的，我在之前的数据中也意识到这个，主要是为了控制假阳性。你可以把binQTL的阈值设置的低些。如果别的方法效果更好，建议你用别的软件或者综合考虑多个软件的结果。

**Comment by Wangchangsh** [comment]
Thanks♪(･ω･)ﾉ
